Repository TCAT-capstone/frontend, pull requests merged in 2022-07, with the labels that each got.

#14 [Feat#13] 티켓 목록 구현 마무리 및 메인 화면 탭 구현
  src/assets/images/like-fill.svg
  src/assets/images/like.svg
  src/components/Common/Header/ProfileDropdown/style.ts
  src/components/Common/Header/style.ts
  src/components/Common/Like/index.tsx
  src/components/Common/Tab/index.tsx
  src/components/Common/Tab/style.ts
  src/components/Ticket/TicketFrame/index.tsx
  src/components/Ticket/TicketFrame/style.ts
  src/components/Ticket/TicketImage/index.tsx
  src/components/Ticket/TicketImage/style.ts
  src/components/Ticket/index.tsx
  src/components/Ticket/style.ts
  src/components/TicketList/Ticket/index.tsx
  src/components/TicketList/Ticket/style.ts
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/pages/MainPage/index.tsx
  src/routes/Router.tsx
  src/styles/Layout/style.ts
  src/styles/media.ts
  src/templates/MainTemplate/index.tsx
  src/templates/MainTemplate/style.ts
  src/utils/constants.ts
Labels: ✨feature, 🎨layout

#16 [Feat#15] 홈화면 UI 구현
  src/assets/images/ticket.svg
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Common/Profile/ProfileBox/style.ts
  src/components/Common/Profile/ProfileIcon/index.tsx
  src/components/Common/Profile/ProfileIcon/style.ts
  src/components/Common/Tab/style.ts
  src/components/TicketList/Ticket/index.tsx
  src/components/TicketList/index.tsx
  src/components/TicketbookList/Ticketbook/index.tsx
  src/components/TicketbookList/Ticketbook/style.ts
  src/components/TicketbookList/index.tsx
  src/components/TicketbookList/style.ts
  src/pages/ErrorPage/index.tsx
  src/pages/HomePage/index.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/MainTemplate/index.tsx
  src/utils/constants.ts
Labels: ♻️refactor, ✨feature, 🎨layout

#18 [Feat#17]
  src/apis/ticket.ts
  src/components/TicketList/Ticket/index.tsx
  src/components/TicketList/Ticket/style.ts
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/pages/HomePage/index.tsx
  src/pages/MainPage/index.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/MainTemplate/index.tsx
  src/types/ticket.ts
  src/utils/fetch.ts
  tsconfig.paths.json
Labels: ♻️refactor, ✨feature, 🎨layout

#22 [Feat#19] 텍스트 에디터 구현 및 상세 페이지 구현
  package.json
  src/apis/image.ts
  src/apis/ticket.ts
  src/assets/images/calendar.svg
  src/assets/images/cast.svg
  src/assets/images/check.svg
  src/assets/images/location.svg
  src/assets/images/seat.svg
  src/assets/images/share.svg
  src/assets/images/ticket-title.svg
  src/components/Common/CheckMark/index.tsx
  src/components/Common/CheckMark/style.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Common/Profile/ProfileIcon/index.tsx
  src/components/Common/TicketInfoBox/index.tsx
  src/components/Common/TicketInfoBox/style.ts
  src/components/TextEditor/index.tsx
  src/components/TextEditor/style.ts
  src/components/TicketList/Ticket/index.tsx
  src/components/TicketList/index.tsx
  src/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/PostPage/index.tsx
  src/pages/WritePage/index.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
  src/styles/editor.css
  src/templates/HomeTemplate/index.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/PostTemplate/index.tsx
  src/templates/PostTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
  src/templates/WriteTemplate/style.ts
  src/types/ticket.ts
  src/utils/fetch.ts
  src/utils/string.ts
  yarn.lock
Labels: ✨feature, 🎨layout

#24 [Deploy] 배포 자동화 테스트
  .github/workflows/main-deploy.yml
Labels: 🚀devops

#25 [Deploy] 배포 자동화 테스트
  .github/workflows/main-deploy.yml
Labels: 🚀devops

#26 [Deploy] 배포 자동화 테스트
  .github/workflows/main-deploy.yml
Labels: 🚀devops

#27 배포 자동화 테스트
  .github/workflows/main-deploy.yml
Labels: 🚀devops

#21 ✨ 프로필관리 페이지 라우터 설정
  src/components/Common/BasicButton/index.tsx
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/ProfileEditor/index.tsx
  src/components/ProfileEditor/style.ts
  src/pages/ProfilePage/index.tsx
  src/routes/Router.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/ProfileTemplate/index.tsx
  src/templates/ProfileTemplate/style.ts
Labels: 🎨layout

#30 [Feat#20-1] Conflict 해결, API 연결
  src/apis/member.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/ProfileEditor/index.tsx
  src/components/ProfileEditor/style.ts
  src/pages/ProfilePage/index.tsx
  src/routes/Router.tsx
  src/templates/ProfileTemplate/index.tsx
  src/templates/ProfileTemplate/style.ts
  src/types/member.ts
Labels: ♻️refactor, ✨feature, 🎨layout

#32 [Feat#31] 로그인 기능 구현
  package.json
  src/App.tsx
  src/apis/member.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Modal/LoginModal/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/OAuthRedirectPage/index.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/stores/user.ts
  src/types/member.ts
  src/utils/constants.ts
  src/utils/fetch.ts
  tsconfig.paths.json
  yarn.lock
Labels: ✨feature

#34 [Fix#33] 로그인 private route오류 해결
  src/routes/PrivateRoute.tsx
Labels: 🐛fixed
