Repository TCAT-capstone/frontend, pull requests merged in 2022-09, with the labels that each got.

#78 [Feat#77] 커스텀 템플릿 구현 및 에러 수정
  package.json
  src/assets/images/loading-cat.png
  src/assets/images/plus-rounded.svg
  src/assets/images/sample-ticket-img.png
  src/assets/images/sample-user-img.jpg
  src/assets/images/template/index.ts
  src/assets/images/twitter.svg
  src/components/Editor/Loading/index.tsx
  src/components/Editor/Loading/style.ts
  src/components/Editor/SideMenu/TemplateMenu/ImageEditModal/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/ImageEditModal/style.ts
  src/components/Editor/SideMenu/TemplateMenu/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/style.ts
  src/components/Editor/SideMenu/index.tsx
  src/components/Modal/LoginModal/index.tsx
  src/components/Modal/LoginModal/style.ts
  src/pages/Editor/EditPage.tsx
  src/pages/PostPage.tsx
  src/stores/editor.ts
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/types/ticket.ts
  yarn.lock
Labels: ✨feature, 🎨layout, 🐛fixed, 🖼️chore

#80 [Feat#79] 템플릿 글자색 변경 & 홈 화면 오류 수정
  src/components/Editor/SideMenu/TextMenu/index.tsx
  src/components/Editor/SideMenu/TextMenu/style.ts
  src/components/Editor/SideMenu/index.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/HomePage.tsx
  src/stores/editor.ts
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
Labels: ✨feature, 🐛fixed

#83 [Feat#81] 좋아요 기능 구현 및 스피너 수정
  src/apis/ticket.ts
  src/assets/images/spinner.gif
  src/components/Common/Spinner/index.tsx
  src/components/Common/Spinner/style.ts
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/pages/PostPage.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/PostTemplate/style.ts
  src/types/ticket.ts
Labels: ✨feature, 🎨layout

#84 [Deploy] 배포
  .github/workflows/main-deploy.yml
  package.json
  src/apis/ticket.ts
  src/assets/images/loading-cat.png
  src/assets/images/plus-rounded.svg
  src/assets/images/sample-ticket-img.png
  src/assets/images/sample-user-img.jpg
  src/assets/images/spinner.gif
  src/assets/images/template/index.ts
  src/assets/images/twitter.svg
  src/components/Common/Spinner/index.tsx
  src/components/Common/Spinner/style.ts
  src/components/Editor/Loading/index.tsx
  src/components/Editor/Loading/style.ts
  src/components/Editor/SideMenu/TemplateMenu/ImageEditModal/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/ImageEditModal/style.ts
  src/components/Editor/SideMenu/TemplateMenu/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/style.ts
  src/components/Editor/SideMenu/TextMenu/index.tsx
  src/components/Editor/SideMenu/TextMenu/style.ts
  src/components/Editor/SideMenu/index.tsx
  src/components/Modal/LoginModal/index.tsx
  src/components/Modal/LoginModal/style.ts
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/pages/Editor/EditPage.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/HomePage.tsx
  src/pages/PostPage.tsx
  src/stores/editor.ts
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/templates/PostTemplate/index.tsx
  src/templates/PostTemplate/style.ts
  src/types/ticket.ts
  yarn.lock
Labels: 🚀devops

#74 [Feat#58] 프로필 드롭다운 티켓북 관리 페이지 메뉴 변경
  src/components/Common/Header/ProfileDropdown/index.tsx
Labels: 🎨layout

#86 [Feat#82] 올바르지 않은 주소, 비로그인 처리
  src/pages/HomePage.tsx
  src/pages/PostPage.tsx
Labels: ✨feature, 🐛fixed

#87 [Feat#38] 검색 페이지 구현
  src/apis/ticket.ts
  src/components/Common/SearchBox/OptionDropdown/index.tsx
  src/components/Common/SearchBox/OptionDropdown/style.ts
  src/components/Common/SearchBox/index.tsx
  src/components/SearchBox/SearchFilter/index.tsx
  src/components/SearchBox/SearchFilter/style.ts
  src/components/SearchBox/index.tsx
  src/components/SearchBox/style.ts
  src/pages/SearchPage.tsx
  src/templates/SearchTemplate/index.tsx
Labels: ✨feature, 🎨layout

#89 [Feat#58] 티켓북 슬라이드 수정
  package.json
  src/apis/ticketbook.ts
  src/assets/images/check-rounded-purple.svg
  src/assets/images/edit.svg
  src/assets/images/seat.svg
  src/components/Editor/SideMenu/TemplateMenu/index.tsx
  src/components/Ticketbook/Ticketbook/index.tsx
  src/components/Ticketbook/Ticketbook/style.ts
  src/components/Ticketbook/TicketbookEditor/index.tsx
  src/components/Ticketbook/TicketbookEditor/style.ts
  src/components/Ticketbook/TicketbookItemList/index.tsx
  src/components/Ticketbook/TicketbookItemList/style.ts
  src/components/Ticketbook/TicketbookSlider/index.tsx
  src/components/Ticketbook/TicketbookSlider/style.ts
  src/components/TicketbookList/Ticketbook/index.tsx
  src/components/TicketbookList/Ticketbook/style.ts
  src/components/TicketbookList/TicketbookExample/index.tsx
  src/components/TicketbookList/index.tsx
  src/hooks/useGetUserInfo.tsx
  src/hooks/useInfiniteScroll.tsx
  src/pages/HomePage.tsx
  src/pages/OAuthRedirectPage.tsx
  src/pages/TicketbookPage.tsx
  src/pages/WritePage.tsx
  src/routes/Router.tsx
  src/stores/user.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
  src/types/ticket.ts
  src/types/ticketbook.ts
  src/utils/constants.ts
  yarn.lock
Labels: ✨feature, 🎨layout

#92 [Fix#91] 라우터 path 오류 해결 및 자잘한 수정
  package.json
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Editor/EditorFrame/index.tsx
  src/components/SearchBox/index.tsx
  src/components/TicketList/index.tsx
  src/pages/WritePage.tsx
  src/routes/Router.tsx
  src/templates/PostTemplate/index.tsx
  yarn.lock
Labels: 🐛fixed

#93 [Deploy] 배포
  package.json
  src/apis/ticket.ts
  src/apis/ticketbook.ts
  src/assets/images/check-rounded-purple.svg
  src/assets/images/edit.svg
  src/assets/images/seat.svg
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Common/SearchBox/OptionDropdown/index.tsx
  src/components/Common/SearchBox/OptionDropdown/style.ts
  src/components/Common/SearchBox/index.tsx
  src/components/Editor/EditorFrame/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/index.tsx
  src/components/SearchBox/SearchFilter/index.tsx
  src/components/SearchBox/SearchFilter/style.ts
  src/components/SearchBox/index.tsx
  src/components/SearchBox/style.ts
  src/components/TicketList/index.tsx
  src/components/Ticketbook/Ticketbook/index.tsx
  src/components/Ticketbook/Ticketbook/style.ts
  src/components/Ticketbook/TicketbookEditor/index.tsx
  src/components/Ticketbook/TicketbookEditor/style.ts
  src/components/Ticketbook/TicketbookItemList/index.tsx
  src/components/Ticketbook/TicketbookItemList/style.ts
  src/components/Ticketbook/TicketbookSlider/index.tsx
  src/components/Ticketbook/TicketbookSlider/style.ts
  src/components/TicketbookList/Ticketbook/index.tsx
  src/components/TicketbookList/Ticketbook/style.ts
  src/components/TicketbookList/TicketbookExample/index.tsx
  src/components/TicketbookList/index.tsx
  src/hooks/useGetUserInfo.tsx
  src/hooks/useInfiniteScroll.tsx
  src/pages/HomePage.tsx
  src/pages/OAuthRedirectPage.tsx
  src/pages/PostPage.tsx
  src/pages/SearchPage.tsx
  src/pages/TicketbookPage.tsx
  src/pages/WritePage.tsx
  src/routes/Router.tsx
  src/stores/user.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/PostTemplate/index.tsx
  src/templates/SearchTemplate/index.tsx
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
  src/types/ticket.ts
  src/types/ticketbook.ts
  src/utils/constants.ts
  yarn.lock
Labels: 🚀devops

#95 [Feat#94] 로딩, 기본 이미지 추가
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/images/default-image-purple.png
  src/assets/images/default-image.png
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Common/Profile/ProfileIcon/index.tsx
  src/components/Common/ShareButton/index.tsx
  src/components/Common/ShareButton/style.ts
  src/components/Ticketbook/TicketbookItemList/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/HomePage.tsx
  src/pages/TicketbookPage.tsx
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
Labels: ✨feature, 🎨layout, 🖼️chore

#96 [Feat#90] 티켓북 슬라이드 반응형 구현
  src/components/Ticketbook/TicketbookSlider/index.tsx
  src/components/Ticketbook/TicketbookSlider/style.ts
Labels: ♻️refactor, 🎨layout, 🐛fixed

#98 [Feat#85] 구독 UI 구현
  src/apis/follow.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/SimpleProfile/index.tsx
  src/components/Common/SimpleProfile/style.ts
  src/components/Common/Tab/FollowTab/index.tsx
  src/components/Common/Tab/FollowTab/style.ts
  src/components/FollowList/index.tsx
  src/components/FollowList/style.ts
  src/components/Modal/ FollowModal/index.tsx
  src/components/Modal/ FollowModal/style.ts
  src/types/member.ts
Labels: ✨feature, 🎨layout
