Repository TCAT-capstone/frontend, pull requests merged in 2022-10, with the labels that each got.

#99 [Feat#97] 공유 버튼 구현, 입력 디바운싱 적용
  src/assets/images/link.svg
  src/assets/images/twitter.svg
  src/components/Common/ShareButton/index.tsx
  src/components/Common/ShareButton/style.ts
  src/components/SearchBox/index.tsx
  src/components/SearchBox/style.ts
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
  src/pages/SearchPage.tsx
  src/templates/SearchTemplate/index.tsx
Labels: ♻️refactor, ✨feature, 🐛fixed

#100 [Feat#85] 구독 리스트 UI 최종 구현
  src/components/Common/Tab/FollowTab/style.ts
  src/components/FollowList/style.ts
  src/components/Modal/FollowModal/style.ts
Labels: 🎨layout

#101 [Deploy] 배포
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/apis/follow.ts
  src/assets/images/default-image-purple.png
  src/assets/images/default-image.png
  src/assets/images/link.svg
  src/assets/images/twitter.svg
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Profile/ProfileBox/index.tsx
  src/components/Common/Profile/ProfileIcon/index.tsx
  src/components/Common/ShareButton/index.tsx
  src/components/Common/ShareButton/style.ts
  src/components/Common/SimpleProfile/index.tsx
  src/components/Common/SimpleProfile/style.ts
  src/components/Common/Tab/FollowTab/index.tsx
  src/components/Common/Tab/FollowTab/style.ts
  src/components/FollowList/index.tsx
  src/components/FollowList/style.ts
  src/components/Modal/FollowModal/index.tsx
  src/components/Modal/FollowModal/style.ts
  src/components/SearchBox/index.tsx
  src/components/SearchBox/style.ts
  src/components/Ticketbook/TicketbookItemList/index.tsx
  src/components/Ticketbook/TicketbookSlider/index.tsx
  src/components/Ticketbook/TicketbookSlider/style.ts
  src/pages/Editor/EditPage.tsx
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
  src/pages/SearchPage.tsx
  src/pages/TicketbookPage.tsx
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/SearchTemplate/index.tsx
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
  src/types/member.ts
Labels: 🚀devops
