Repository TCAT-capstone/frontend, pull requests merged in 2022-11, with the labels that each got.

#104 [Fix#103] 버그 처리
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
  src/pages/Editor/EditPage.tsx
Labels: 🐛fixed

#105 [Feat#85] 구독 기능 구현
  src/apis/follow.ts
  src/components/Common/FollowButton/index.tsx
  src/components/Common/FollowButton/style.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/SimpleProfile/index.tsx
  src/components/Modal/FollowModal/index.tsx
  src/pages/HomePage.tsx
  src/templates/HomeTemplate/index.tsx
  src/types/member.ts
Labels: ✨feature

#106 [Feat#102] 모바일 UI 구현
  src/components/Common/TicketInfoBox/style.ts
  src/components/TicketList/Ticket/style.ts
  src/templates/PostTemplate/style.ts
Labels: 🎨layout

#107 [Feat#102] 모바일 기준 사이즈 변경
  src/components/Common/TicketInfoBox/style.ts
  src/components/TicketList/Ticket/style.ts
  src/styles/media.ts
  src/templates/PostTemplate/style.ts
Labels: 🎨layout

#108 [Feat#85] 후기 페이지 구독 기능 구현, 구독 페이지 닫기 버튼 오류 해결
  src/components/Common/SimpleProfile/index.tsx
  src/components/Modal/ModalFrame/style.ts
  src/templates/PostTemplate/index.tsx
  src/types/member.ts
Labels: ✨feature, 🐞bug

#110 [Feat#109] 피드 기능 구현
  src/apis/ticket.ts
  src/pages/MainPage.tsx
Labels: ✨feature

#111 [Deploy] 배포
  src/apis/follow.ts
  src/apis/ticket.ts
  src/components/Common/FollowButton/index.tsx
  src/components/Common/FollowButton/style.ts
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/SimpleProfile/index.tsx
  src/components/Common/TicketInfoBox/style.ts
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
  src/components/Modal/FollowModal/index.tsx
  src/components/Modal/ModalFrame/style.ts
  src/components/TicketList/Ticket/style.ts
  src/pages/Editor/EditPage.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/styles/media.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/PostTemplate/style.ts
  src/types/member.ts
Labels: 🚀devops

#112 [Feat#102] 구독 페이지, 티켓홈 페이지 모바일 UI 구현
  src/components/Common/Profile/ProfileIcon/style.ts
  src/components/Common/SimpleProfile/style.ts
  src/components/FollowList/style.ts
  src/components/Modal/ModalFrame/style.ts
  src/components/Ticketbook/Ticketbook/style.ts
  src/components/Ticketbook/TicketbookSlider/style.ts
  src/templates/HomeTemplate/style.ts
Labels: 🎨layout

#113 [Feat#102] 모바일 UI 개발로 인한 오류 해결
  src/components/Common/Profile/ProfileIcon/style.ts
  src/components/Common/SimpleProfile/style.ts
  src/components/FollowList/style.ts
  src/components/Modal/LoginModal/style.ts
  src/components/Modal/ModalFrame/style.ts
Labels: 🎨layout, 🐞bug

#114 [Deploy] 배포
  public/index.html
  src/components/Common/Profile/ProfileIcon/style.ts
  src/components/Common/SimpleProfile/style.ts
  src/components/FollowList/style.ts
  src/components/Modal/LoginModal/style.ts
  src/components/Modal/ModalFrame/style.ts
  src/components/Ticketbook/Ticketbook/style.ts
  src/components/Ticketbook/TicketbookSlider/style.ts
  src/templates/HomeTemplate/style.ts
Labels: 🚀devops

#117 [Feat#85] homeId 불러오기 위한 중복 코드 삭제
  src/components/Common/SimpleProfile/index.tsx
  src/components/Modal/FollowModal/index.tsx
Labels: ♻️refactor

#116 [Feat#115] 이미지 압축
  package.json
  src/components/TextEditor/index.tsx
  src/pages/TicketbookPage.tsx
  src/pages/WritePage.tsx
  src/utils/image.ts
  yarn.lock
Labels: ♻️refactor, ✨feature

#118 [Deploy] 배포
  package.json
  src/components/Common/SimpleProfile/index.tsx
  src/components/Modal/FollowModal/index.tsx
  src/components/TextEditor/index.tsx
  src/pages/TicketbookPage.tsx
  src/pages/WritePage.tsx
  src/utils/image.ts
  yarn.lock
Labels: 🚀devops

#119 [Feat#102] 프로필 관리, 검색 페이지 모바일 UI 구현
  src/components/Common/Profile/ProfileBox/style.ts
  src/components/ProfileEditor/style.ts
  src/components/SearchBox/SearchFilter/style.ts
  src/components/SearchBox/style.ts
  src/pages/SearchPage.tsx
  src/templates/ProfileTemplate/style.ts
Labels: ✨feature, 🎨layout

#120 [Feat#102] 티켓북 수정 페이지 모바일 UI 구현, 자잘한 버그 해결
  src/components/TicketList/style.ts
  src/components/Ticketbook/Ticketbook/style.ts
  src/templates/TicketbookTemplate/style.ts
Labels: 🎨layout, 🐞bug

#121 [Deploy] 배포
  src/components/Common/Profile/ProfileBox/style.ts
  src/components/ProfileEditor/style.ts
  src/components/SearchBox/SearchFilter/style.ts
  src/components/SearchBox/style.ts
  src/components/TicketList/style.ts
  src/components/Ticketbook/Ticketbook/style.ts
  src/pages/SearchPage.tsx
  src/templates/ProfileTemplate/style.ts
  src/templates/TicketbookTemplate/style.ts
Labels: 🚀devops

#125 [Feat#122] 검색 이동 기능 구현
  src/components/Common/TicketInfoBox/index.tsx
  src/components/Common/TicketInfoBox/style.ts
  src/pages/SearchPage.tsx
  src/utils/string.ts
Labels: ✨feature

#127 [Feat#124] 구독 버튼 초기화 오류 해결, 비로그인 시 구독 버튼 해제
  src/pages/HomePage.tsx
  src/pages/PostPage.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
Labels: 🐞bug

#128 [Deploy] 배포
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/pages/PostPage.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
Labels: 🚀devops

#130 [Fix#129] 기타 오류 해결
  src/assets/images/template/index.ts
  src/assets/images/template/interpark.jpg
  src/assets/images/template/interpark.png
  src/assets/images/template/melon.jpg
  src/assets/images/template/melon.png
  src/assets/images/template/yes24.jpg
  src/assets/images/template/yes24.png
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/WritePage.tsx
  src/templates/RegisterTemplate/index.tsx
  src/templates/RegisterTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
Labels: 🐛fixed

#131 [Deploy] 배포
  src/assets/images/template/index.ts
  src/assets/images/template/interpark.jpg
  src/assets/images/template/interpark.png
  src/assets/images/template/melon.jpg
  src/assets/images/template/melon.png
  src/assets/images/template/yes24.jpg
  src/assets/images/template/yes24.png
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/WritePage.tsx
  src/templates/RegisterTemplate/index.tsx
  src/templates/RegisterTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
Labels: 🚀devops

#132 [Deploy] 배포
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
Labels: 🚀devops

#134 [Feat#133] 메인 페이지 하단에 노션 이동 버튼 추가
  src/assets/images/help.png
  src/templates/MainTemplate/index.tsx
  src/templates/MainTemplate/style.ts
Labels: ✨feature, 🎨layout, 🖼️chore

#135 [Deploy] 배포
  README.md
  src/assets/images/help.png
  src/components/Common/SimpleProfile/index.tsx
  src/components/Modal/FollowModal/index.tsx
  src/templates/MainTemplate/index.tsx
  src/templates/MainTemplate/style.ts
Labels: 🚀devops
