Repository TCAT-capstone/frontend, pull requests merged in 2022-08, with the labels that each got.

#37 [Feat#36] 에디터 페이지 구현
  package.json
  src/assets/images/template/interpark.png
  src/assets/images/template/melon.png
  src/assets/images/template/yes24.png
  src/components/Editor/EditorFrame/index.tsx
  src/components/Editor/EditorFrame/style.ts
  src/components/Editor/SideMenu/Tab/index.tsx
  src/components/Editor/SideMenu/Tab/style.ts
  src/components/Editor/SideMenu/TemplateMenu/index.tsx
  src/components/Editor/SideMenu/TemplateMenu/style.ts
  src/components/Editor/SideMenu/TextMenu/index.tsx
  src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
  src/components/Editor/SideMenu/TicketInfoMenu/style.ts
  src/components/Editor/SideMenu/index.tsx
  src/components/Editor/SideMenu/style.ts
  src/components/TextEditor/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/pages/OAuthRedirectPage.tsx
  src/pages/PostPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/WritePage.tsx
  src/pages/WritePage/index.tsx
  src/routes/Router.tsx
  src/stores/editor.ts
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/templates/Editor/NewTemplate/index.tsx
  src/templates/Editor/NewTemplate/style.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/WriteTemplate/index.tsx
  src/utils/constants.ts
  yarn.lock
Labels: ✨feature

#39 [Feat#38] 검색 페이지 구현
  src/apis/ticket.ts
  src/assets/images/down-arrow.svg
  src/assets/images/x-black.svg
  src/components/Common/SearchBox/OptionDropdown/index.tsx
  src/components/Common/SearchBox/OptionDropdown/style.ts
  src/components/Common/SearchBox/index.tsx
  src/components/Common/SearchBox/style.ts
  src/pages/SearchPage.tsx
  src/routes/Router.tsx
  src/templates/SearchTemplate/index.tsx
Labels: ✨feature, 🎨layout

#41 ⚡️ 헤더 돋보기 클릭 시 검색 페이지 이동
  src/components/Common/Header/index.tsx
Labels: ✨feature

#43 🐛 헤더 프로필 드롭다운 상자 크기 조정
  src/components/Common/Header/ProfileDropdown/style.ts
Labels: 🎨layout, 🐛fixed

#44 [Feat#35] 가입 시 유저 정보 입력 화면 개발, 유저 정보 연동
  src/apis/member.ts
  src/assets/images/check-rounded.svg
  src/assets/images/error-rounded.svg
  src/assets/images/lock.svg
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Editor/EditorFrame/index.tsx
  src/components/ProfileEditor/index.tsx
  src/components/ProfileEditor/style.ts
  src/pages/HomePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/RegisterPage.tsx
  src/routes/RegisterRoute.tsx
  src/routes/Router.tsx
  src/templates/ProfileTemplate/index.tsx
  src/templates/RegisterTemplate/index.tsx
  src/templates/RegisterTemplate/style.ts
  src/types/member.ts
  src/utils/constants.ts
  src/utils/fetch.ts
Labels: ✨feature, 🎨layout

#46 [Feat#45] 회원가입 중복 아이디 처리, 사진 Drag & Drop 업로드, OCR 서버 연동
  src/apis/member.ts
  src/apis/ticket.ts
  src/components/Editor/DragDrop/index.tsx
  src/components/Editor/DragDrop/style.ts
  src/components/Editor/EditorFrame/index.tsx
  src/components/Editor/Loading/index.tsx
  src/components/Editor/Loading/style.ts
  src/components/TicketList/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/RegisterPage.tsx
  src/routes/Router.tsx
  src/templates/Editor/EditTemplate/index.tsx
  src/templates/Editor/EditTemplate/style.ts
  src/templates/Editor/NewTemplate/index.tsx
  src/templates/Editor/NewTemplate/style.ts
  src/templates/PostTemplate/index.tsx
  src/types/member.ts
  src/types/ticket.ts
  src/utils/fetch.ts
Labels: ♻️refactor, ✨feature, 🎨layout, 🐛fixed

#48 [Feat#47] 페이지 레이아웃 크기 수정
  src/templates/ProfileTemplate/style.ts
Labels: 🎨layout, 🐛fixed

#54 [Feat#53] 티켓홈 진입 시 티켓북 목록 첫 위치 수정
  src/components/TicketbookList/index.tsx
  src/components/TicketbookList/style.ts
Labels: 🎨layout, 🐛fixed

#60 [Feat#55] 티켓홈 티켓북 개수 적을 시 UI 오류
  src/components/TicketbookList/TicketbookExample/index.tsx
  src/components/TicketbookList/index.tsx
  src/components/TicketbookList/style.ts
  src/templates/HomeTemplate/index.tsx
  src/types/ticket.ts
Labels: 🎨layout, 🐛fixed

#61 [Feat#59] 무한스크롤 구현
  src/apis/ticket.ts
  src/assets/images/spinner.gif
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/hooks/useInfiniteScroll.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/templates/HomeTemplate/index.tsx
  src/templates/MainTemplate/index.tsx
  src/templates/SearchTemplate/index.tsx
  src/types/ticket.ts
  tsconfig.paths.json
Labels: ♻️refactor, ✨feature

#62 [Feat#51] 글쓰기 티켓북 설정 구현, 글쓰기 API 연동
  src/apis/ticket.ts
  src/apis/ticketbook.ts
  src/components/Common/BasicButton/index.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/WritePage.tsx
  src/templates/WriteTemplate/index.tsx
  src/templates/WriteTemplate/style.ts
  src/types/ticket.ts
  src/types/ticketbook.ts
Labels: ✨feature, 🎨layout

#64 [Feat#63] 글 삭제, 수정
  src/apis/ticket.ts
  src/pages/PostPage.tsx
  src/pages/WritePage.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/WriteTemplate/index.tsx
  src/types/ticket.ts
Labels: ✨feature

#66 [Feat#65] 글쓰기 Validation
  package.json
  src/App.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/WritePage.tsx
  yarn.lock
Labels: ✨feature

#68 [Feat#57] 404 에러 페이지 수정
  src/assets/images/error-404.png
  src/assets/images/error-paw.png
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/pages/ErrorPage.tsx
  src/pages/TicketbookPage.tsx
  src/routes/Router.tsx
  src/templates/ErrorTemplate/index.tsx
  src/templates/ErrorTemplate/style.ts
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
Labels: ✨feature, 🎨layout

#69 [Feat#56] 프로필 수정 코드 리팩토링, 조건 추가
  src/components/ProfileEditor/index.tsx
  src/components/ProfileEditor/style.ts
  src/pages/ProfilePage.tsx
  src/templates/ProfileTemplate/index.tsx
Labels: ♻️refactor, ✨feature, 🐛fixed

#70 [Feat#56] 프로필 수정 페이지 오류 해결
  src/components/Common/Profile/ProfileBox/style.ts
  src/components/ProfileEditor/style.ts
  src/pages/ProfilePage.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/ProfileTemplate/style.ts
Labels: 🎨layout, 🐛fixed

#71 [Deploy] 배포
  package.json
  src/App.tsx
  src/apis/ticket.ts
  src/apis/ticketbook.ts
  src/assets/images/error-404.png
  src/assets/images/error-paw.png
  src/assets/images/spinner.gif
  src/components/Common/BasicButton/index.tsx
  src/components/Common/Header/ProfileDropdown/index.tsx
  src/components/Common/Profile/ProfileBox/style.ts
  src/components/Common/TicketInfoBox/index.tsx
  src/components/ProfileEditor/index.tsx
  src/components/ProfileEditor/style.ts
  src/components/TicketList/Ticket/style.ts
  src/components/TicketList/index.tsx
  src/components/TicketList/style.ts
  src/components/TicketbookList/Ticketbook/index.tsx
  src/components/TicketbookList/Ticketbook/style.ts
  src/components/TicketbookList/TicketbookExample/index.tsx
  src/components/TicketbookList/index.tsx
  src/components/TicketbookList/style.ts
  src/hooks/useInfiniteScroll.tsx
  src/pages/Editor/EditPage.tsx
  src/pages/Editor/NewPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/MainPage.tsx
  src/pages/PostPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/TicketbookPage.tsx
  src/pages/WritePage.tsx
  src/routes/Router.tsx
  src/templates/ErrorTemplate/index.tsx
  src/templates/ErrorTemplate/style.ts
  src/templates/HomeTemplate/index.tsx
  src/templates/HomeTemplate/style.ts
  src/templates/MainTemplate/index.tsx
  src/templates/PostTemplate/index.tsx
  src/templates/ProfileTemplate/index.tsx
  src/templates/ProfileTemplate/style.ts
  src/templates/SearchTemplate/index.tsx
  src/templates/TicketbookTemplate/index.tsx
  src/templates/TicketbookTemplate/style.ts
  src/templates/WriteTemplate/index.tsx
  src/templates/WriteTemplate/style.ts
  src/types/ticket.ts
  src/types/ticketbook.ts
  tsconfig.paths.json
  yarn.lock
Labels: 🚀devops

#72 [Feat#57] 404 페이지 헤더 삭제
  src/templates/ErrorTemplate/index.tsx
  src/templates/ErrorTemplate/style.ts
Labels: 🎨layout

#73 [Feat#56] 화면 작을 시 바이오 줄바꿈 삭제
  src/components/Common/Profile/ProfileBox/style.ts
Labels: 🎨layout

#75 [Deploy] 배포
  src/components/Common/Profile/ProfileBox/style.ts
  src/pages/HomePage.tsx
  src/templates/ErrorTemplate/index.tsx
  src/templates/ErrorTemplate/style.ts
Labels: 🚀devops
